#!/usr/bin/env bash
# This script gives information about the school file

if [ -e school ]
then
  echo "school file exists"
else
  echo "school file does not exist"
fi

if [ -f school ]
then
  echo "school is a regular file"
fi

if [ -d school ]
then
  echo "school is a directory"
fi

if [ -s school ]
then
  echo "school is not empty"
else
  echo "school is empty"
fi
